name: Check codes

on:
  - push

jobs:
  path-filter:
    timeout-minutes: 5
    outputs:
      # keep-sorted start
      actions: ${{steps.changes.outputs.actions}}
      demo: ${{steps.changes.outputs.deno}}
      renovate: ${{steps.changes.outputs.renovate}}
      # keep-sorted end
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            flake:
              - flake.nix
              - flake.lock
            renovate:
              - renovate.json5
            actions:
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
            deno:
              - **/*.ts
  check-deno:
    needs: path-filter
    if: needs.path-filter.outputs.deno == 'true' || needs.path-filter.outputs.flake == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command deno task fmt:check
      - run: nix develop --command deno task check
      - run: nix develop --command deno task lint

  deno_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      - run: deno task fmt:check
  deno_check:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      - run: deno task check
  deno_lint:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      - run: deno task lint
